# Generated by Django 3.0.3 on 2022-03-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=150, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=17, null=True)),
                ('find_us', models.CharField(blank=True, max_length=150, null=True)),
                ('work_industry', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
